### ISSUE TITLE
Write smart contract [Help]

### ISSUE THREAD

**Issue by Ruttanachote** [chnejohnson/vue-dapp#118]
How to call smart contract (write contract send params function) to open metamask call and response to modal in vue.js template

**Comment by re2005** [comment]
Hi @Ruttanachote please next time submit these kind of question inside `Discussions`.

In order to call a SC methods you need first to instantiate the contract. You should use `ethers` lib.
```ts
import { Contract } from 'ethers';
import { useEthers } from 'vue-dapp';

const { signer } = useEthers();
const contract = new Contract(address, abi, signer);
```
Where `address` is the contract address and `abi` is the JSON interface from that contract.

Once you have instantiate the contract your variable `contract` will contain all contract methods, than you can just invoke any method passing it's arguments.

Hope it helped, cheers.
