### ISSUE TITLE
"Disconnect" button when closing "WalletConnect" and "Coinbase Wallet" modals but not really connected.

### ISSUE THREAD

**Issue by re2005** [chnejohnson/vue-dapp#77]
The issue happens when you select to connect using `WalletConnect` or `Coinbase Wallet`

If you just close the modal, you will see the `disconnect` button as if you were connected.

https://user-images.githubusercontent.com/2920357/186440497-1ffca409-2eac-4cdd-9b1f-2c2dafbfc8d3.mov

**Comment by chnejohnson** [comment]
I will fix this. Refer to https://github.com/chnejohnson/vue-dapp/pull/69/files

**Comment by chnejohnson** [comment]
@semantic-release-bot  Cool!
@re2005 Now if you want to publish a new npm version, you have to add the last commit like `ci(release): <your-release-message>` so that when the PR merged, @semantic-release-bot will help you publish it :) 

The release rule is written [here](https://github.com/chnejohnson/vue-dapp/blob/650b021d3834fece88309b63781a2fe6369fda23/.releaserc.json#L6-L10)
